# Generated by Django 4.2.20 on 2025-06-13 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0003_alter_assignedquiz_id_alter_choice_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assignedquiz",
            unique_together={("quiz", "user")},
        ),
    ]
